### ISSUE TITLE
Are Flows and PowerApps which are not connected to CDS affected during the upgrade?

### ISSUE THREAD

**Issue by jjinatlanta** [MicrosoftDocs/common-data-model-and-service#13]
Will Flows (and PowerApps) not connected to CDS continue to run normally during the migration?
If non-CDS Flows do not run during the migration, will they be triggered after migration is complete, or will those runs be missed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08497d1c-0527-bd2a-3500-d2df3b5b9736
* Version Independent ID: 08cb8ab9-9610-fdcd-ae24-c40b3fc1e484
* Content: [Upgrade and verify your apps and flows](https://docs.microsoft.com/en-us/common-data-service/upgradecds/upgrade-verify-apps-flows)
* Content Source: [common-data-service/upgradecds/upgrade-verify-apps-flows.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/upgrade-verify-apps-flows.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Flows and PowerApps (now called canvas apps) not connected to the previous version of CDS will not be affected during the upgrade. They should continue to run uninterrupted during the migration.
