### ISSUE TITLE
Apps not prompting to be updated

### ISSUE THREAD

**Issue by CaivanNisha** [MicrosoftDocs/common-data-model-and-service#14]
I completed step 1 (my environment had an "Upgrade now" link) and created a test environment on Feb 21. However, no emails were received by the owners and when i open my apps in the studio, I don't get any prompts to upgrade it. There is also nothing listed under "Resource Copies".  How do i proceed to step 2?

**Comment by KumarVivek** [comment]
@CaivanNisha Can you please report the issue on product repo: https://github.com/Microsoft/CDM/issues

Closing the issue.
