### ISSUE TITLE
Reset upgrade

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/common-data-model-and-service#15]
My customers tenant shows a Reset upgrade button. I don't see this mentioned in the documentation. Will clicking this have any affect on objects in production?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9c429-7db9-e07b-475b-88e01c605912
* Version Independent ID: 194ca6f2-7356-804b-d342-b6b457ca5adf
* Content: [Errors and resolutions when upgrading previous version of Common Data Service.](https://docs.microsoft.com/en-us/common-data-service/upgradecds/errors-resolutions)
* Content Source: [common-data-service/upgradecds/errors-resolutions.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/errors-resolutions.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
The Reset upgrade button appears when a step fails and must be re-started.

**Comment by KumarVivek** [comment]
Closing the issue.
