### ISSUE TITLE
add a note for Project Roadmap admins

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/common-data-model-and-service#17]
this article is linked from the Project Roadmap rollout instructions; would help to add a note for Project Roadmap admins who may not know what DCS is or how to find out who is using it and just want to unblock turning it on for their tenant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5a90b1-c5c1-9bc4-f6ad-0b80f24ec45c
* Version Independent ID: 9e758061-5a18-7bbd-78a5-04b60ab31f1f
* Content: [Upgrade to Common Data Service for Apps](https://docs.microsoft.com/en-us/common-data-service/upgradecds/introduction-upgrade-cds)
* Content Source: [common-data-service/upgradecds/introduction-upgrade-cds.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/introduction-upgrade-cds.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
Closing this issue as the product this issue is about is no longer supported/exists.
