### ISSUE TITLE
Finding Affected App Owners

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/common-data-model-and-service#18]
How do we find the apps that are going to be affected so that we can notify the owners of the outage and what they will need to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5a90b1-c5c1-9bc4-f6ad-0b80f24ec45c
* Version Independent ID: 9e758061-5a18-7bbd-78a5-04b60ab31f1f
* Content: [Upgrade to Common Data Service for Apps](https://docs.microsoft.com/en-us/common-data-service/upgradecds/introduction-upgrade-cds)
* Content Source: [common-data-service/upgradecds/introduction-upgrade-cds.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/introduction-upgrade-cds.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
When you complete Step 1 there will be a list of affected apps and flows. You will need to work with them to have the apps and flows migrated. The only outage will occur in Step 3 when the actual upgrade is finalized.

If you don't want to perform Step 1, you can contact support and they can perform a query on your behalf that will retrieve affected apps and flows.
