### ISSUE TITLE
Finding affected Flows

### ISSUE THREAD

**Issue by Yashuaaa** [MicrosoftDocs/common-data-model-and-service#19]
What if we aren't using any PowerApps?

For example, we just have a couple **SharePoint List(s)** that are using a Flow. Do SharePoint Lists count as "Apps" and do they use the CDS database?

How can we find out which Flow(s) are using the CDS database without starting the upgrade? We shouldn't have to complete step 1 of an upgrade if we **dont need to upgrade in the first place.**

Thoughts?

**Comment by JimDaly** [comment]
Sorry for the delay in responding. 
This content explains how to find out if any apps or flows are using the CDS 1.0 database.

https://review.docs.microsoft.com/en-us/common-data-service/upgradecds/start-upgrade-process?branch=master#how-do-i-know-whether-any-apps-or-flows-use-this-database
