### ISSUE TITLE
A self-service signup plan is required to successfully complete this request. e3499ddd-b502-40e0-989b-faa47f162273

### ISSUE THREAD

**Issue by mwucbs** [MicrosoftDocs/common-data-model-and-service#20]
i Cant upgrade because of this error. maybe others have the same error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9c429-7db9-e07b-475b-88e01c605912
* Version Independent ID: 194ca6f2-7356-804b-d342-b6b457ca5adf
* Content: [Errors and resolutions when upgrading previous version of Common Data Service.](https://docs.microsoft.com/en-us/common-data-service/upgradecds/errors-resolutions)
* Content Source: [common-data-service/upgradecds/errors-resolutions.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/errors-resolutions.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by mwucbs** [comment]
OMG i found a solution.
We have edu O365 tenant with O365 powerapps license.
1: remove all licenses from your admin account.
2: Sign up for a free trial / purchase powerapps P2 ( i did trial)
2.1: if you getting error: Your IT department has turned off signup
Then connect to your tenant with powershell ( msol),
View setting with:  Get-MsolCompanyInformation | fl allow*
Set setting with: Set-MsolCompanySettings -AllowAdHocSubscriptions $true
Now setup trial subscription with your admin account, and disable adhoc subscription afterwards.
3. Now upgrade your database :)

**Comment by JimDaly** [comment]
Added content about this flow https://docs.microsoft.com/en-us/common-data-service/upgradecds/errors-resolutions#self-service-signup-plan-is-required
