### ISSUE TITLE
Cannot create test database while upgrading exsisting CDS database

### ISSUE THREAD

**Issue by mwucbs** [MicrosoftDocs/common-data-model-and-service#21]
OMG i found a solution.
We have edu O365 tenant with O365 powerapps license.
1: remove all licenses from your admin account.
2: Sign up for a free trial / purchase powerapps P2 ( i did trial)
2.1: if you getting error: Your IT department has turned off signup
Then connect to your tenant with powershell ( msol),
View setting with:  Get-MsolCompanyInformation | fl allow*
Set setting with: Set-MsolCompanySettings -AllowAdHocSubscriptions $true
Now setup trial subscription with your admin account, and disable adhoc subscription afterwards.
3. Now upgrade your database :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5a90b1-c5c1-9bc4-f6ad-0b80f24ec45c
* Version Independent ID: 9e758061-5a18-7bbd-78a5-04b60ab31f1f
* Content: [Upgrade to Common Data Service for Apps](https://docs.microsoft.com/en-us/common-data-service/upgradecds/introduction-upgrade-cds)
* Content Source: [common-data-service/upgradecds/introduction-upgrade-cds.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/introduction-upgrade-cds.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
I hope this helps someone, but I'm afraid I'm not clear on the problem it is solving.

**Comment by JimDaly** [comment]
Now that I understand how this issue occurs, we have added content to support this flow. See https://docs.microsoft.com/en-us/common-data-service/upgradecds/errors-resolutions#self-service-signup-plan-is-required
