### ISSUE TITLE
Page update date

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/common-data-model-and-service#23]
It says "11/21/2019" :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fd0c77d-a4f2-17ce-20a5-b4e9a780e801
* Version Independent ID: 2e000b44-142c-42f9-022f-9a41f95d6b64
* Content: [Frequently asked questions - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/faq#feedback)
* Content Source: [common-data-model/faq.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/faq.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @a-zaf!
