### ISSUE TITLE
No link to Upgrade page for CDS Upgrade

### ISSUE THREAD

**Issue by LarryBolton** [MicrosoftDocs/common-data-model-and-service#25]
I'm on the Environments page in the PowerApps - Admin center for my tenant. I see one environment that needs to be upgraded, because it has (Upgrade) next to the Name, but it's no a link to the Upgrade page.

![image](https://user-images.githubusercontent.com/12585809/55901319-1dd1f880-5b97-11e9-9b7d-12ff8c7374e9.png)

I've checked using Edge, IE 11 and Chrome - they all display the same thing. 

I have the PowerApp Plan 2 license. It's a trial license, but it's active.

I eventually ended up in the Dynamics 365 Administration Center and on the Environments page there and I get the same results. I can see that the Environment needs to be upgraded but there is no link to the Upgrade page.

Has the Upgrade page link expired?  

Is there another way to get to the Upgrade page? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b280f390-2bac-be3f-b1f5-9b0c5185d9fb
* Version Independent ID: a682003e-cd92-abae-b8d2-54502f5f3698
* Content: [Upgrade to Common Data Service for Apps](https://docs.microsoft.com/en-us/common-data-service/upgradecds/start-upgrade-process#feedback)
* Content Source: [common-data-service/upgradecds/start-upgrade-process.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/start-upgrade-process.md)
* Service: **commondataservice**
* Technology: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
The fact that it has "(Upgrade)" in the name suggests it was already upgraded.

When CDS databases only existed to support flow approvals, we have been upgrading them automatically.

Only those databases which support apps or flows need to be upgraded by an administrator.
