### ISSUE TITLE
Can't find Remove-LegacyCDSDatabase command

### ISSUE THREAD

**Issue by e-gallis** [MicrosoftDocs/common-data-model-and-service#26]
Hello,
Following the exact steps in this article I could not find the command called Remove-LegacyCDSDatabase.
Was it renamed ? Is the article still up-to-date ?
Thanks,
Emmanuel

**Comment by JimDaly** [comment]
I could verify that it is there:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> Install-Module -Name Microsoft.PowerApps.Administration.PowerShell
PS C:\WINDOWS\system32> Remove-LegacyCDSDatabase /?

cmdlet Remove-LegacyCDSDatabase at command pipeline position 1
Supply values for the following parameters:
DatabaseId:
```

**Comment by e-gallis** [comment]
Hi Jim,
Sorry to bother you again but I definitely can't access the cmdlet on my side as you can see on the capture. What am I doing wrong ?
![image](https://user-images.githubusercontent.com/32480338/56443950-04e3e880-62f7-11e9-9ac6-49068e8d7779.png)
