### ISSUE TITLE
Parsing model.json

### ISSUE THREAD

**Issue by ptansey** [MicrosoftDocs/common-data-model-and-service#27]
Are there any tools available for parsing the contents of the model.json file? We'd like to create SQL tables based on the data and meta-data found in our CDM folders, but generating the required CREATE TABLE commands based on the meta data is proving tedious without a proper tool to parse the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce95c65c-2b6d-cca3-ff37-db6d5bfe818d
* Version Independent ID: 2e2cd63e-ae99-811d-3b09-ec3e54b700f2
* Content: [Metadata format - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/model-json)
* Content Source: [common-data-model/model-json.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/model-json.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by AFTOwen** [comment]
Thanks, @ptansey. You might find what you're looking for [here](https://github.com/Microsoft/CDM/tree/master/samples/cdm-folders).

**Comment by ptansey** [comment]
Thank you for your reply. We had to create our own app using the Newtonsoft.Json library to parse the model.json file.
In the end I asked the wrong question. I now realize we want to know how to read the model.json file and CDM folders with Azure Data Factory. I'll ask that question in a more appropriate space, though.
