### ISSUE TITLE
sign up form Error

### ISSUE THREAD

**Issue by rarif1** [MicrosoftDocs/common-data-model-and-service#29]
Hi, the sign-up form is failing to submit due to a validation error on the Industry field. Even when populated the form is failing to submit. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669597ce-c8fb-9ea4-597e-801f4a6f6cbf
* Version Independent ID: d2a15bc6-a39c-e34b-a3d7-79c2bbf8ad4e
* Content: [Industry Accelerators - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/industry-accelerators#feedback)
* Content Source: [common-data-model/industry-accelerators.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/industry-accelerators.md)
* Service: **common-data-model**
* GitHub Login: @smithy7
* Microsoft Alias: **smithc**

**Comment by MSFTMan** [comment]
@smithy7 Thanks for reporting this issue. I see that the link isn't working. I'll look into this and follow up.

**Comment by MSFTMan** [comment]
@smithy7 We've fixed this issue. Thank you for reporting it.
