### ISSUE TITLE
How was the CDM Schema diagram created?

### ISSUE THREAD

**Issue by emeria** [MicrosoftDocs/common-data-model-and-service#31]
I am working on my own solutions data model schema and really like how the CDM is presented here.  Was the "CDMPoster_a3.pdf" image created manually in Visio or are there tools to generate an image from a data model, similar to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e58fef-52e9-244a-2390-434f21ae36eb
* Version Independent ID: 6093a1c5-b58e-07d7-813a-a13887610bc5
* Content: [The Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/#feedback)
* Content Source: [common-data-model/index.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/index.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by oovanesy** [comment]
the diagram is an illustration created manually to provide visual representation of different subject areas and the approach of the Common Data Model

**Comment by makdaddy8888** [comment]
This looks like Adobe Illustrator or Adobe Indesign

**Comment by MSFTMan** [comment]
@emeria Thanks for reporting this issue. Per @oovanesy, the diagram is manually created.
