### ISSUE TITLE
Managed vs unmanaged accelerator solutions

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/common-data-model-and-service#32]
Hi, 

  what is the recommended approach for using managed vs unmanaged accelerator solutions? Wondering if the idea is that we should be using unmanaged in dev to, then, include everything we need into our own solutions(then export etc), or if we should be using managed to take a dependency on them in our solutions (then install those managed accelerators in every environment where we need them first)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669597ce-c8fb-9ea4-597e-801f4a6f6cbf
* Version Independent ID: d2a15bc6-a39c-e34b-a3d7-79c2bbf8ad4e
* Content: [Industry Accelerators - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/industry-accelerators)
* Content Source: [common-data-model/industry-accelerators.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/industry-accelerators.md)
* Service: **common-data-model**
* GitHub Login: @smithy7
* Microsoft Alias: **smithc**

**Comment by smithy7** [comment]
Alex,
We recommend that you only use the managed solutions. Let me clarify a few points:

1. The Accelerators have 3 main components (CDM extensions, Data Integrations components, sample applications). We want partners to always include the managed CDM solutions in their applications - similar to taking a dependency on any other first party solutions.

2. The sample apps are NOT designed for production use; hence why we shipped the un-managed solutions

Thanks,

-Smith

Get Outlook for Mobile

________________________________

**Comment by KumarVivek** [comment]
Closing the issue.
