### ISSUE TITLE
Model.json instead of model.json

### ISSUE THREAD

**Issue by benjguin** [MicrosoftDocs/common-data-model-and-service#33]
In https://docs.microsoft.com/en-us/common-data-model/data-lake#common-data-model-folders, the name "Model.json" is used instead of "model.json".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbbce1d-7475-6655-df5d-f52c77732c25
* Version Independent ID: 25b5905e-8253-4c65-64a7-da2e408076a0
* Content: [Microsoft Azure Data Lake Storage Gen2 - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/data-lake)
* Content Source: [common-data-model/data-lake.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/data-lake.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by oovanesy** [comment]
Thank you, Benjamin, I've scanned the page and could not find Model.json. Could you please paste specific text fragment with it?

**Comment by oovanesy** [comment]
Hello and thank for the question! Yes, it is possible not to have all assets in the same folder. However, our suggestion is based on ease of managing files as they land in the lake and not running into issues when there is no access/revoked access to a different file location.

**Comment by MSFTMan** [comment]
@benjguin Thanks for reporting this issue. I've scanned this file and this issue has been fixed.
