### ISSUE TITLE
Formatting is broken.

### ISSUE THREAD

**Issue by pflickin** [MicrosoftDocs/common-data-model-and-service#35]
The Instances area is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a335b2-413d-106c-d336-10ff33c9317d
* Version Independent ID: d3a805dc-544b-ac72-b3e7-5f49a958b8dd
* Content: [EventRegistration - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/schema/core/applicationcommon/foundationcommon/crmcommon/solutions/marketing/eventmanagement/eventregistration#feedback)
* Content Source: [common-data-model/schema/core/applicationCommon/foundationCommon/crmCommon/solutions/marketing/eventManagement/EventRegistration.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/schema/core/applicationCommon/foundationCommon/crmCommon/solutions/marketing/eventManagement/EventRegistration.md)
* Service: **common-data-model**
* GitHub Login: @nenad1002
* Microsoft Alias: **nebanfic**

**Comment by MSFTMan** [comment]
@pflickin Thanks for reporting this issue. Can you provide a bit more information about what is broken or missing?

**Comment by MSFTMan** [comment]
> @pflickin Thanks for reporting this issue. Can you provide a bit more information about what is broken or missing?

@pflickin Thanks for reporting this issue. Since we haven't gotten a response from you, we'll close this issue. Kindly let us know if you are still having a problem.
