### ISSUE TITLE
Where can you find these entities in the Power BI Dataflows "Map to Standard" capability?

### ISSUE THREAD

**Issue by crisher0219** [MicrosoftDocs/common-data-model-and-service#36]
I am unable to locate any of the **financialCommon** entities in the "Map to Standard" capability. Is there a way to get these entities? I have also posted a similar thread to the GitHub repo (https://github.com/microsoft/CDM/issues/96). I wasn't clear on the scope here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d38915-6f32-4dd0-5b48-e96d6b4da33b
* Version Independent ID: 503120b5-24fa-84c0-6a88-cfc89298aeaa
* Content: [overview - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/schema/core/applicationcommon/foundationcommon/financialcommon/overview)
* Content Source: [common-data-model/schema/core/applicationCommon/foundationCommon/financialCommon/overview.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/schema/core/applicationCommon/foundationCommon/financialCommon/overview.md)
* Service: **common-data-model**
* GitHub Login: @nenad1002
* Microsoft Alias: **nebanfic**

**Comment by oovanesy** [comment]
Hello,
Thank you for the interest in Common Data Model. 
The set of entities available at map to standard experience does not include all standard entities yet. We are working on rectifying this issue
