### ISSUE TITLE
Is is possible to apply the model.json on multiple data lakes vs just one?

### ISSUE THREAD

**Issue by isamllr** [MicrosoftDocs/common-data-model-and-service#39]
Is it possible to apply one model.json for multiple Data Lakes vs just one?

**Comment by MSFTMan** [comment]
@isamllr Thanks for reporting this issue. We're looking into it and will update here when we have a resolution.

**Comment by oovanesy** [comment]
Hi isamllr,
Could you please provide more deals about the scenario you are working on? Information about model.json - https://docs.microsoft.com/en-us/common-data-model/model-json

**Comment by MSFTMan** [comment]
@isamllr We are closing this issue because we haven't gotten a response from you. Please reopen the issue as needed.
