### ISSUE TITLE
Common Data Model Poster link is broken

### ISSUE THREAD

**Issue by HoloBeard** [MicrosoftDocs/common-data-model-and-service#43]
The link that takes you to CDMPoster_a3.pdf is broken but on the Git Hub end. When you get to the Git Hub site the PDF is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e58fef-52e9-244a-2390-434f21ae36eb
* Version Independent ID: 6093a1c5-b58e-07d7-813a-a13887610bc5
* Content: [The Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/)
* Content Source: [common-data-model/index.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/index.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by KumarVivek** [comment]
@HoloBread This is fixed now. Closing the issue.
