### ISSUE TITLE
model.json filename

### ISSUE THREAD

**Issue by fhtino** [MicrosoftDocs/common-data-model-and-service#44]
Is model.json the mandatory file name for a json file describing the model and partitions?
In some cases it could be very useful to have 2 or more model.json files pointing to a different number of partition.

Example:
\model_a.json  
\model_b.json
\data\file1.csv
\data\file2.csv
...
\data\file99.csv

model_a.json points to partition  1...99 and model_b.jon only points to partition 1...5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce95c65c-2b6d-cca3-ff37-db6d5bfe818d
* Version Independent ID: 2e2cd63e-ae99-811d-3b09-ec3e54b700f2
* Content: [Metadata format - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/model-json)
* Content Source: [common-data-model/model-json.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/model-json.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by oovanesy** [comment]
model.json is name by design. however, our updated metadata format supports manifests and submanifest as well. and you can also use multiple manifests per folder. I recommend to keep CDM Folder to a specific area of data as it is easier to manage

**Comment by MSFTMan** [comment]
@fhtino Thanks for reporting this issue. Please see earlier response from @oovanesy
