### ISSUE TITLE
Minor typo 

### ISSUE THREAD

**Issue by jonsing** [MicrosoftDocs/common-data-model-and-service#49]
In the code snippet section after “You'll then create uaBrowserVersion, which is also a string type:” it contains a repeated attribute of browserName instead of showing browserName and then uaBroswerVersion as attribute names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eddd936c-13a7-fe05-9333-44a834a25392
* Version Independent ID: 3c9594c6-956f-2bae-125e-9f607ef4a258
* Content: [Create schema documents for the Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/creating-schemas#feedback)
* Content Source: [common-data-model/creating-schemas.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/creating-schemas.md)
* Service: **common-data-model**
* GitHub Login: @jinichu
* Microsoft Alias: **jibyun**

**Comment by KumarVivek** [comment]
@jonsing  This issue is fixed. Closing the issue.
