### ISSUE TITLE
Language and Currency for Database

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/common-data-model-and-service#5]
Hi, is possible mention to somewhere the impacts of the Language and Currency when creating the upgrade database for new environment? Is possible to find out the current one settings for current database which is default instance? I mean that this cannot be changed after if I am correct.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 6f26d686-f83c-4270-f57f-effd314be30f
* Version Independent ID: 6d3b0e99-1b18-c6ab-8829-1bba77947e64
* Content: [Overview of the upgrade process](https://docs.microsoft.com/cs-cz/common-data-service/upgradecds/upgrade-overview)
* Content Source: [common-data-service/upgradecds/upgrade-overview.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/upgrade-overview.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
The previous version of CDS didn't have the concepts of Language and Currency built in.
The only documentation I can find for this is [Create a Common Data Service for Apps database](https://docs.microsoft.com/en-us/powerapps/administrator/create-database) and it doesn't provide much more information.

But you are correct. This can't be changed once you create the database.
The language is the base language for the system. Use the language that your administrators and customizers will want to use day-to-day. Additional languages can be enabled for users later, but all the administration and customization will be done in the base language.

For currency, I looked  around for some official docs on this, but this older blog post is probably the most comprehensive explanation I could find [Understanding organization’s base currency in Dynamics 365 (CRM)](https://themscrmexpert.wordpress.com/2016/12/29/understanding-organizations-base-currency-in-dynamics-365-crm/). I hope this helps.

**Comment by Kazzan** [comment]
Hi @JimDaly, thanks for great links. I mean that these hints should be mentioned in article. For example, as an administrator I do not see easily setup of original database. So some hints, recommendations and these links how to setup will be really great.

**Comment by KumarVivek** [comment]
Closing this issue as the product this issue is about is no longer supported/exists.
