### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by interfacemirror** [MicrosoftDocs/common-data-model-and-service#51]
Some spelling mistakes on the page. For example, defintion is typed incorrectly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8086e6b-8013-81bc-0595-3bec0c1ba6e9
* Version Independent ID: 50540c83-6de8-c81a-4590-a968bdc3b5f9
* Content: [Usage - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/use)
* Content Source: [common-data-model/use.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/use.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by MSFTMan** [comment]
@interfacemirror  Thanks for reporting this issue. It has been fixed.
