### ISSUE TITLE
Relationships - attributeName property

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/common-data-model-and-service#54]
Too many commas, in the attributeName property it includes a comma at the end of the sentence which throws an error.

Section: https://docs.microsoft.com/en-us/common-data-model/model-json#relationships

Incorrect
 "relationships": [
        {
            "$type": "SingleKeyRelationship",
            "fromAttribute": {
                "entityName": "Account",
                "attributeName": "ContactId",
           },
            "toAttribute": { 
                "entityName": "Contact",
                "attributeName": "Id",
           }
        },
    ]

Correct:
 "relationships": [
        {
            "$type": "SingleKeyRelationship",
            "fromAttribute": {
                "entityName": "Account",
                "attributeName": "ContactId"
           },
            "toAttribute": { 
                "entityName": "Contact",
                "attributeName": "Id"
           }
        },
    ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce95c65c-2b6d-cca3-ff37-db6d5bfe818d
* Version Independent ID: 2e2cd63e-ae99-811d-3b09-ec3e54b700f2
* Content: [Metadata format - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/model-json#relationships)
* Content Source: [common-data-model/model-json.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/model-json.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by MSFTMan** [comment]
@itsnotaboutthecell Thanks for reporting this issue. It is now fixed. You will see it live shortly.
