### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by avenizelos** [MicrosoftDocs/common-data-model-and-service#55]
In the paragraph "Because it imported MyDefintions.cdm.json, this new document can reference the symbols for personFullName and any symbols from the foundations.cdm.json document, such as entityId." the name MyDefintions.cdm.json is not spelled correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d4ae87-6945-1f97-3181-6778400bb574
* Version Independent ID: d14e498c-9b44-2c4f-ee6a-2b8fb01062ca
* Content: [Technical details of Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/sdk/fundamentals#feedback)
* Content Source: [common-data-model/sdk/fundamentals.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/sdk/fundamentals.md)
* Service: **common-data-model**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@avenizelos Thanks for reporting this issue. It's fixed now.
