### ISSUE TITLE
OrderedBy purpose definition refers to ordering by an entity, but should be by an attribute

### ISSUE THREAD

**Issue by billgib** [MicrosoftDocs/common-data-model-and-service#57]
In the entry below in Standard Purpose Objects section, the explanation should be "...ordered by default by this *attribute*"

orderedBy | The records of the entity can be ordered by default by this entity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f765fe-c882-24fc-19e3-79d800ddb030
* Version Independent ID: 1029ed07-dac1-00d3-fff1-33af6c1c579d
* Content: [The Common Data Model logical definitions - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/sdk/logical-definitions)
* Content Source: [common-data-model/sdk/logical-definitions.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/sdk/logical-definitions.md)
* Service: **common-data-model**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**the Purpose

**Comment by MSFTMan** [comment]
@billgib Thanks for reporting this issue. We'll investigate and fix as necessary.

**Comment by MSFTMan** [comment]
@billgib This issue is now fixed. Thank you!
