### ISSUE TITLE
Broken link at end of 'Using an entity as the type of an attribute' section

### ISSUE THREAD

**Issue by billgib** [MicrosoftDocs/common-data-model-and-service#58]
The link to 'Converting logical entities into resolved entities' is broken, with the link code visible on the page 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f765fe-c882-24fc-19e3-79d800ddb030
* Version Independent ID: 1029ed07-dac1-00d3-fff1-33af6c1c579d
* Content: [The Common Data Model logical definitions - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/sdk/logical-definitions#traits-applied-to-attributes)
* Content Source: [common-data-model/sdk/logical-definitions.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/sdk/logical-definitions.md)
* Service: **common-data-model**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@billgib  Thanks! We'll get this fixed.

**Comment by MSFTMan** [comment]
@billgib This is is now fixed. Thank you.
