### ISSUE TITLE
ERROR: database that was soft-deleted

### ISSUE THREAD

**Issue by erombalski** [MicrosoftDocs/common-data-model-and-service#6]
After successfully deleting a v1.0 database using the above procedure, upon clicking [Create my database] button:

&lt;begin scary red box&gt;
! The environment xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx has a database that was soft-deleted: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.
&lt;/end scary red box&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1304e571-7ea2-68af-e4d3-17cae0bf309c
* Version Independent ID: 14ffcbf2-b736-c48a-a355-5fe340a4a994
* Content: [Delete your previous version Common Data Service database](https://docs.microsoft.com/en-us/common-data-service/upgradecds/delete-legacy-cds-database)
* Content Source: [common-data-service/upgradecds/delete-legacy-cds-database.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/delete-legacy-cds-database.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
That's not expected. The 'soft-delete' just means that the database was disconnected to the environment.  But you should be able to create a new database. Can you try again? There might have been some delay in enabling creating a new database. If not, please contact support and let them know your environmentid (It is in the URL when you view the environment on admin.powerapps.com.).
