### ISSUE TITLE
where's the PDF?

### ISSUE THREAD

**Issue by knyhus** [MicrosoftDocs/common-data-model-and-service#61]
I'd like to download as a PDF, like most other MS articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 741fc9c7-0dca-9701-bc4b-962645ab2f00
* Version Independent ID: b1da3225-1d1a-3381-987c-59c605256512
* Content: [Nonprofit Accelerator - Dynamics 365 - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/nfp-accelerator#feedback)
* Content Source: [common-data-model/NFP-accelerator.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/NFP-accelerator.md)
* Service: **common-data-model**
* GitHub Login: @lponti
* Microsoft Alias: **lponti**

**Comment by MSFTMan** [comment]
@knyhus Thanks for reporting this issue. This repo doesn't currently offer pdf downloads. We'll consider adding support. Thanks!
