### ISSUE TITLE
Second diagram in the corpus section needs redrawing to replace references to common data model with CDM

### ISSUE THREAD

**Issue by billgib** [MicrosoftDocs/common-data-model-and-service#62]
There was a moment I think when a source document was edited by mistake to change all references to "cdm" to "common data model".  This diagram seems to have been changed in line with that.  Please review all references in the diagram to 'common data model' and verify if they should be replaced with the acronym, 'cdm' .  The imports statement shown is one example that should be cdm:/foundations.cdm.json, not as written currently 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d4ae87-6945-1f97-3181-6778400bb574
* Version Independent ID: d14e498c-9b44-2c4f-ee6a-2b8fb01062ca
* Content: [Technical details of Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/sdk/fundamentals#the-corpus)
* Content Source: [common-data-model/sdk/fundamentals.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/sdk/fundamentals.md)
* Service: **common-data-model**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@billgib Thanks for reporting this issue. We'll get it fixed.
