### ISSUE TITLE
Deleted User

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/common-data-model-and-service#7]
And what is the option when encounter error "Can't find XRM ID for user..." when the user was already deleted? Remove the permissions from database and re-run upgrade (which seems to stuck in an Error state)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9c429-7db9-e07b-475b-88e01c605912
* Version Independent ID: 194ca6f2-7356-804b-d342-b6b457ca5adf
* Content: [Errors and resolutions when upgrading previous version of Common Data Service.](https://docs.microsoft.com/en-us/common-data-service/upgradecds/errors-resolutions)
* Content Source: [common-data-service/upgradecds/errors-resolutions.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/errors-resolutions.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
I am getting reports that this error occurs when users who are referred to in the previous version CDS 1.0 database have left the company. The user referred to by the oid is no longer in the tenant Azure Active Directory. I don't know that this is the only reason, but it seems one condition that could trigger this.  Removing references to those users in the permissions for the database and re-running the upgrade seems like a good strategy.

**Comment by Kazzan** [comment]
Hi @JimDaly, we remove references in permissions of database and apps, but the upgrade still failing. Do you mean that clean also all Flows or shares apps is needed?

**Comment by KumarVivek** [comment]
Closing this issue as the product this issue is about is no longer supported/exists.
