### ISSUE TITLE
Cannot access the blog post in https://docs.microsoft.com/en-us/common-data-model/banking-accelerator

### ISSUE THREAD

**Issue by isharailanga** [MicrosoftDocs/common-data-model-and-service#70]
This page refers a blog post : https://https/cloudblogs.microsoft.com/dynamics365/bdm/2019/07/17/microsoft-dynamics-365-banking-accelerator-is-now-generally-available/
Cannot access the above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313a5e36-ab14-e02d-b6e5-b935eae42fc5
* Version Independent ID: 33df222f-b766-67eb-e398-fac3433a5f73
* Content: [Dynamics 365 financial services accelerator banking component - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/banking-accelerator)
* Content Source: [common-data-model/banking-accelerator.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/banking-accelerator.md)
* Service: **common-data-model**
* GitHub Login: @jamesgalvin
* Microsoft Alias: **jgalvin**

**Comment by MSFTMan** [comment]
@isharailanga Thanks for reporting this issue. It is now fixed.
