### ISSUE TITLE
Broken AppSoruce URL - 404

### ISSUE THREAD

**Issue by koger23** [MicrosoftDocs/common-data-model-and-service#73]
File: [MicrosoftDocs
/
common-data-model-and-service/README.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/hied-accelerator.md)

Line 116 AppSource with wrong URL: https://appsource.microsoft.com/product/dynamics-365/mshied.highereducationcommondatamodel?tab=Overview

Right URL: https://appsource.microsoft.com/en-us/product/dynamics-365/mshied.educationcommondatamodel?tab=Overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d7de2a-88ce-c549-b28c-5c035a904b44
* Version Independent ID: 12426cca-3145-8431-9bdb-81b20f5489d9
* Content: [Dynamics 365 education accelerator higher education component - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/hied-accelerator)
* Content Source: [common-data-model/hied-accelerator.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/hied-accelerator.md)
* Service: **common-data-model**
* GitHub Login: @meenoorami
* Microsoft Alias: **merami**

**Comment by MSFTMan** [comment]
@koger23 Thanks for reporting this issue. It's now fixed.
