### ISSUE TITLE
Appsource link is brokesays 404 Error

### ISSUE THREAD

**Issue by manishdvmske** [MicrosoftDocs/common-data-model-and-service#74]
Hi Team, 
Greetings, 
I was checking the blog and got error when clicked on App source link. Error is 404. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac9f789-5ad0-f970-4559-1b697c5aee04
* Version Independent ID: b6f6e8f9-b6a5-5d9a-724e-bc9ea532ace4
* Content: [Dynamics 365 education accelerator K-12 - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/edu-k12-accelerator)
* Content Source: [common-data-model/edu-k12-accelerator.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/edu-k12-accelerator.md)
* Service: **common-data-model**
* GitHub Login: @meenoorami
* Microsoft Alias: **merami**

**Comment by MSFTMan** [comment]
@manishdvmske Thanks for reporting this issue. It's fixed.
