### ISSUE TITLE
Dynamics 365 education accelerator link goes to 404 page

### ISSUE THREAD

**Issue by leestack** [MicrosoftDocs/common-data-model-and-service#76]
Hey everyone, the Dynamics 365 education accelerator link goes to 404 page.

Thanks, Lee

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d7de2a-88ce-c549-b28c-5c035a904b44
* Version Independent ID: 12426cca-3145-8431-9bdb-81b20f5489d9
* Content: [Dynamics 365 education accelerator higher education component - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/hied-accelerator#common-data-model-extensions)
* Content Source: [common-data-model/hied-accelerator.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/hied-accelerator.md)
* Service: **common-data-model**
* GitHub Login: @meenoorami
* Microsoft Alias: **merami**

**Comment by meenoorami** [comment]
Hi
I have fixed this error and waiting for pull request to be approved.

Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MSFTMan** [comment]
@leestack This issue is now fixed. Thank you.
