### ISSUE TITLE
404 on Appsource links

### ISSUE THREAD

**Issue by correnasergent** [MicrosoftDocs/common-data-model-and-service#77]
Both app source links (top and bottom) return a 404 not found error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d7de2a-88ce-c549-b28c-5c035a904b44
* Version Independent ID: 12426cca-3145-8431-9bdb-81b20f5489d9
* Content: [Dynamics 365 education accelerator higher education component - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/hied-accelerator)
* Content Source: [common-data-model/hied-accelerator.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/hied-accelerator.md)
* Service: **common-data-model**
* GitHub Login: @meenoorami
* Microsoft Alias: **merami**

**Comment by MSFTMan** [comment]
@correnasergent Thanks for reporting this issue. We've fixed the app source link. The other link will be fixed shortly.
