### ISSUE TITLE
Owners of apps and flows have not received e-mail

### ISSUE THREAD

**Issue by jhitfrombit** [MicrosoftDocs/common-data-model-and-service#8]
Yesterday (02/12/19) I initiated the upgrade process which finished creating the test environment in 3½ hours. Today (02/13/19) the owners of the apps and flows have not received any e-mail asking them to test their apps and flows. There are mail enabled user accounts connected to the them - not only security groups. Does that mean that there are no apps or flows connected to old database?

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 08497d1c-0527-bd2a-3500-d2df3b5b9736
* Version Independent ID: 08cb8ab9-9610-fdcd-ae24-c40b3fc1e484
* Content: [Upgrade and verify your apps and flows](https://docs.microsoft.com/da-dk/common-data-service/upgradecds/upgrade-verify-apps-flows)
* Content Source: [common-data-service/upgradecds/upgrade-verify-apps-flows.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-service/upgradecds/upgrade-verify-apps-flows.md)
* Service: **commondataservice**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
We found that these emails were not getting sent and a fix was applied late last week, unfortunately too late for you to benefit. But in the list of affected apps and flows, you should see the owner of the apps and flow so that you can contact them directly.
People who are just starting now should have the emails sent.

**Comment by jjinatlanta** [comment]
Can you clarify where the "list of affected apps and flows" can be found? Is that displayed in the section titled "Resource copies" which appears after the test database has been created?

**Comment by CaivanNisha** [comment]
Hi there. I created the test environment (step 1), but when i open up my apps it doesn't notify me that they need to be upgraded. There are also no items listed in the "resource copies" list. I am not sure how to proceed to step 2?

**Comment by adab3** [comment]
Hi. I have created the test environment as well (step 1). The process started yesterday (28th February at 2pm) and it has finished today (1st of March at 3:30am). That is more than 12 hours... Also creators of apps or flows have NOT received any email explaining step 2. I have created a flow myself and I have been not been notified.

is this becouse the Flows/apps that we have created are not affected by the database upgrade?

**Comment by GrantCocco** [comment]
I am also the owner of several Power Apps and Flows yet I have not seen any emails regarding testing or upgrading apps while running the first phase on a demo database or during the prep of our default production database.

**Comment by JimDaly** [comment]
@jjinatlanta The list of affected apps and flows is shown in the screenshot in [Next Steps](https://docs.microsoft.com/en-us/common-data-service/upgradecds/start-upgrade-process#next-step)

Also, I understand that support now has a tool that can perform this query for you without starting Step 1. Send them the URL you use to access the environment with your request.

**Comment by JimDaly** [comment]
@CaivanNisha Were there any apps or flows listed as affected resources at the bottom of the page when you completed step 1? It could be that you have no apps or flows that connect to the previous version of CDS.

**Comment by JimDaly** [comment]
@adab3 : If the Apps or flows do not connect to the previous version of CDS, they will not be affected and no emails will be sent out. The emails will not be sent until Step 1 completes.

**Comment by JimDaly** [comment]
@GrantCocco Do your apps and flows connect to the previous version CDS database? If not, you will not receive any emails.

**Comment by GrantCocco** [comment]
Hi Jim,  oops, your messages were ending up in Junk Mail for me. Sorry for the delay responding.  I went through the upgrade process twice using two production databases.  The first being a sandbox environment built by a person who has left our company. There were no apps or flows associated with this environment so I quickly built a basic flow and simple canvas Power app prior to testing the upgrade process.   The second upgrade was the default database for our Microsoft 365 tenancy.  In both cases I saw nothing listed for Resource copies.  We can reasonably presume that no one in our organization had built any model driven Power apps or advanced flows.  Both upgrades reported success.  Time to take Power Platform to the next level for us.  I'll begin my learning journey here: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro.
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro>

What is Common Data Service for Apps? - PowerApps | Microsoft Docs<https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro>
Common Data Service (CDS) for Apps lets you securely store and manage data that's used by business applications. Data within CDS for Apps is stored within a set of entities. An entity is a set of records used to store data, similar to how a table stores data within a database. CDS for Apps includes ...
docs.microsoft.com

Nice work, thank you!
Grant R. Cocco CISSP
[cid:336c6e6d-48b9-467b-ad62-e3ee28b3e101]


________________________________

**Comment by lightupdifire** [comment]
Hello,
We started update today 12 March, no mails received too. We don't have a lot of apps and flows in Default CDS, so maybe question would be can we proceed next step 3 without doing anything in Step 2 and finalize upgrade?

**Comment by JimDaly** [comment]
Yes. The only flows or apps you need to be concerned about are those which connect to the previous version CDS database. All your apps and flows that use other connectors are not impacted.

**Comment by lightupdifire** [comment]
@JimDaly,
Thanks.

@All who run update,

Just my experience:
1. We don't have a lot apps (20+-) and flows (50+-)
2. Run Upgrade as per instruction
3. On Step1 got Error: "There were errors initiating the database upgrade."
4. Restarted process
5. Step 1 completed
6. Mails not sent to flow or apps owners, so click Next on Step2 and it went to process Step3
7. On Step3 failed with same error: "There were errors initiating the database upgrade."
8. Restarted process
9. Failed again on Step3 with same error
10. Restarted process and it completed with 1x warning

In result:

1. CDS DB updated ok
2. CDS DB has now strange name, checking how to rename it
3. In Dynamic 365 created 3x same name instances, (one match to the one I upgrade) all those three were not there (in Dynamic 365) before, checking with support if we should remove them or what to do with them now.

Good luck all :)

**Comment by KumarVivek** [comment]
Closing this issue as the product this issue is about is no longer supported/exists.
